# Site settings
title: Graham Troyer-Joy
description: I am an empathic, open-minded leader; a curious, pragmatic problem-solver; an artist who ships.

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
